/* budgie-1.0.vapi generated by valac 0.22.1, do not modify. */

namespace Budgie {
	[CCode (cheader_filename = "panelconfig.h")]
    public extern const string MODULE_DIRECTORY;

	[CCode (cheader_filename = "panelconfig.h")]
    public extern const string MODULE_DATA_DIRECTORY;
}
